version: '3.3'

volumes:
  postgres_data: {}

services:
  rails:
    build:
      context: .
      dockerfile: ./compose/rails/Dockerfile
    depends_on:
        - postgres
    volumes:
      - ./rails-backend:/app
      - ./stored_procedures:/stored_procedures
    env_file:
      - ./.envs/.rails
      - ./.envs/.postgres
    ports:
      - "3000:3000"
    command: /start

  postgres:
    image: postgres:12.3
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./stored_procedures:/stored_procedures
    env_file:
      - ./.envs/.postgres
    ports:
      - "5432:5432"

  chrome:
    image: selenium/standalone-chrome:latest
    container_name: chrome
    volumes:
      - /dev/shm:/dev/shm
    ports:
      - "4444:4444"

  # redis:
  #   image: redis:6.2.1
  #   ports:
  #     - "6379:6379"
