
development:
  adapter: postgresql
  encoding: unicode
  host: <%= ENV.fetch("POSTGRES_HOST") %>
  database: <%= ENV.fetch("POSTGRES_DB") %>
  pool: 5
  username: <%= ENV.fetch("POSTGRES_USER") %>
  password: <%= ENV.fetch("POSTGRES_PASSWORD") %>

test:
  adapter: postgresql
  encoding: unicode
  host: <%= ENV.fetch("POSTGRES_HOST") %>
  database: <%= ENV.fetch("POSTGRES_DB_TEST") %>
  pool: 5
  username: <%= ENV.fetch("POSTGRES_USER_TEST") %>
  password: <%= ENV.fetch("POSTGRES_PASSWORD_TEST") %>
